version: "3.9"

services:
  mlproject:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: workflow-ci-container
    volumes:
      - ../MLProject:/app
    ports:
      - "5000:5000"  # contoh, jika nanti ada API
    environment:
      - PYTHONUNBUFFERED=1
